### ISSUE TITLE
Implementing topic offset

### ISSUE THREAD

**Issue by tnolet** [sclasen/akka-kafka#17]
Hi,

I would love to be able to set the initial offset in time, i.e. reading from the starts or just reading new messages since the current moment. I'm implementing some Kafka readers that are not interested in any backed up messages, just the message that are arriving from the moment the readers attached. Any tips on how this could be done?

Thanks!

**Comment by sclasen** [comment]
@tnolet gonna close this one, feel free to reopen if this is still an issue

**Comment by carneles** [comment]
Hi @sclasen,

I found this post when I'm trying to find the answer of my problem. So basically, this is the situation I face:
I have many akka-kafka implementation in the system, most of them, read the message from the beginning (set the "auto.offset.reset = smallest" in the configuration file). However, there is one implementation that should only read the latest message (ignore the old messages). Because AkkaConsumer class will always take "auto.offset.reset" from configuration file, I created an extender class named ConfigurableAkkaConsumer (-- extend from AkkaConsumer), override the kafkaConsumerProps() inside the class and injecting "auto.offset.reset=largest" configuration there.
When I printed/debug the configuration of latest implementation, I found it already use "auto.offset.reset = largest" which is what I expected. However, when I run it, it still read old messages.
Then I found this post, I tried to implement your suggestion above (suggestion no 1), but just like @tnolet, I cannot receive any message when trying to set CommitConfig(None, None).

Really hope you can give me some enlightenment.

**Comment by sclasen** [comment]
Have you tried creating a seperate actor system with a seperate config, then you could configure like is described here, https://github.com/sclasen/akka-kafka#configure, but passing a different conf file in.

How is your code different than the test here?  https://github.com/sclasen/akka-kafka/blob/master/src/it/scala/com/sclasen/akka/kafka/NonCommitingConsumerSpec.scala

Never got feedback from tnolet on that, but it appears to work as expected in the test
