### ISSUE TITLE
Guidance Requested: Error Handling

### ISSUE THREAD

**Issue by msaffitz** [sclasen/akka-kafka#47]
Hello,

Thanks for the great library.  I'm using the basic `AkkaConsumer` actor and am hoping you can provide guidance on error handling within the receive method.  Specifically, we're handling the messages and writing to a DB system.  Occasionally we receive an timeout from the underlying DB that manifests as an exception.  It appears that this then causes that message to not properly send a `StreamFSM.Processed` event (which seems correct, since it the message was not processed).  This then ultimately causes our consumer to hang in an infinite committing state.

What's the best way to handle messages such that the message will be retried to another actor?  Do we need to handle all possible error cases in `receive`, or is there some event we can send to the `sender` to trigger a retry?

Thanks in advance.

**Comment by sclasen** [comment]
Hi Michael

Yes, you do need to handle all error cases.

The consumer only counts the number of outstanding messages and will hang
infinitely at commit time if you don't ack each message your actor had
received.

There is no way for the consumer to tell that you have processed each
message otherwise.

If an error in your processing is ok then you can send back an ack at that
time.

Thanks!

**Comment by msaffitz** [comment]
Thanks-- I really appreciate the guidance.
